environments:
  default:
    values:
      - version: 11.2.3

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
  
releases:
- name: prometheus
  namespace: prometheus
  chart: stable/prometheus
  version: {{ .Values.version }}
