---
- hosts: webservers

  tasks:
  - name: Create a data container - 1
    docker_container:
      name: test1
      image: alpine:3.11
        
  - name: Create a data container - 2
    community.docker.docker_container:
      name: test2
      image: busybox:1.32.0

  - name: Create a data container - 3
    docker_container:
      name: test3
      image: busybox:1.32.0
